[package]
name = "sp1-decompression-script"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
sp1-decompression-core = { workspace = true, features = ["std"] }
sp1-sdk = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
